config/routes.rb
Rails.application.routes.draw do
  
  

  resources :articles do
    resources :comments
  end
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :commenter, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update]
	def index
  	@articles = Article.all 
  end

	def new
		@article = Article.new
	end

	def create
		@article = Article.create(article_params)
  end

  def edit
  end

  def update
    @article.update_attributes(article_params)
	end

  def show
  	@article = Article.find(params[:id])
  end

	def destroy
  	@article = Article.find(params[:id])
  	@article.destroy
 		redirect_to articles_path
	end
	
  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def set_article
    @article  = Article.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
 	private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= tinymce %>
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
        <% @article.errors.full_messages.each do |msg| %>
          <p class="text-danger" ><%= msg %></p>
        <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_field :title ,class: "form-control", placeholder: "Title"%>
  </div>
  <div class="form-group">
    <%= f.text_area :text,:class => "tinymce" %>
  </div>
  <div class="form-group">
    <%= f.button :submit, class: "btn btn-primary " %>
  </div>
 
<% end %>

app/views/articles/_update.html.erb
<h1><%= @article.title %></h1>
<p>
  <%= @article.text.html_safe %>
</p>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 

<div class="row">
   <% @articles.each do |article| %>
    <div class="col-md-14 ">
      <div class="panel panel-info">
        <div class="panel-heading">
          <%= article.title %><br>
          <small>
          <%= link_to article_path(article) do %>
            created <%= time_ago_in_words(article.created_at) %>
          <% end %>
          </small>
        </div>
        <div class="panel-body">
          <%= article.text.html_safe %>
        </div>
        <div class="panel-footer">
          <%= link_to 'Show', article_path(article) %> |
          <%= link_to 'Edit', edit_article_path(article) %> |
          <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
      </div>
    </div>
    <% end %>
</div>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
 
<p>
  <%= @article.text.html_safe %>
</p>
<br><hr>
<h4>Comments</h4>
<%= render @article.comments %>
<hr>
<h4>Add a comment:</h4>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/update.js.erb
$('#edit-article').html("<%= j (render 'update') %>");
$('#edit-article').slideDown(700);

app/views/comments/_comment.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= comment.commenter %>
    <%= link_to 'Delete Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-right"%>
  </div>
  <div class="panel-body">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.text_field :commenter,class: "form-control", placeholder: "Commenter" %>
  </p>
  <p>
    <%= f.text_area :body,class: "form-control", placeholder: "Comment" %>
  </p>
  <p>
    <%= f.button :submit, class: "btn btn-primary", value: "Comment" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>